name: Provision AWS Resources

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  DB_MASTER_PASSWORD: ${{ secrets.DB_MASTER_PASSWORD }}

jobs:
  create_aws_resource:
    name: Create Resource
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create resources
        run: |
          cd cf-stacks
          ./stack-helper.sh ${DB_MASTER_PASSWORD}
